name: Create EKS Cluster

on: workflow_dispatch

env:
  AWS_REGION: us-east-1
  NODE_TYPE: t3.medium
  GIT_OWNER: Kirti160598
  GIT_REPO: flux-with-helm
  NODE_COUNT: 1
  GIT_BRANCH: main
  K8S_VERSION: "1.28"
  CLUSTER_NAME: github-eks-cluster  # You can make this dynamic too, if needed

jobs:
  create-eks:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install eksctl
        run: |
          curl --silent --location "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -Ls https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
      - name: Install Flux CLI
        run: |
          curl -s https://fluxcd.io/install.sh | sudo bash
          
      - name: Flux Bootstrap GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.FLUX_GITHUB_TOKEN }}
        run: |
          flux bootstrap github \
            --owner=$GIT_OWNER \
            --repository=$GIT_REPO \
            --branch=$GIT_BRANCH \
            --path=clusters/$CLUSTER_NAME \
            --personal
